language: python
python:
  - "3.8"

install:
  - export PYTHONPATH=/home/travis/build/help1101/epam_final_project/departments_app/
  - pip install -r requirements.txt

script:
  - pytest
  - coverage report

after_success:
  - coveralls

