language: python
python:
  - "3.8"

install:
  - export PYTHONPATH=/home/travis/build/help1101/epam_final_project
  - pip install -r requirements.txt

script:
  - pytest

after_success:
  - coveralls

